container:
  image: defn/dev:ci

precommit_task:
  script: |
    chown -R ubuntu:ubuntu "${CIRRUS_WORKING_DIR}"
    sudo -E -u ubuntu ~ubuntu/bin/e ./ci/precommit.sh

golang_task:
  modules_cache:
    fingerprint_script: md5sum go.sum
    folder: ${CIRRUS_WORKING_DIR}/go/pkg/mod
  get_script: env GOPATH=${CIRRUS_WORKING_DIR}/go ~/bin/e go get ./...
  build_script: env GOPATH=${CIRRUS_WORKING_DIR}/go ~/bin/e go build ./...

python_task:
  script: |
    chown -R ubuntu:ubuntu "${CIRRUS_WORKING_DIR}"
    sudo -E -u ubuntu ~ubuntu/bin/e ./ci/python.sh
