test:
	pre-commit
	cd "$(shell pwd -P)" && if ! cirrus run --container-lazy-pull --output simple; then figlet failed | /usr/games/lolcat; false; fi
	cd "$(shell pwd -P)" && if ! earthly +meh; then figlet failed | /usr/games/lolcat; false; fi
	rm -f .test
	git push
	@figlet success | /usr/games/lolcat
