name: Run Cirrus Tasks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cirrus:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: cirruslabs/cirrus-action@v2
